### ISSUE TITLE
Create workspace window's terminal is too narrow

### ISSUE THREAD

**Issue by vsavkin** [nrwl/angular-console#285]
The width is set to 80 on the backend. So the UI element has to be at least 80 wide for the progress bars to work.

**Comment by mrmeku** [comment]
Fixed via https://github.com/nrwl/angular-console/pull/308

**Comment by vsavkin** [comment]
@mrmeku  I still see the issue. Maybe we are talking 2 different thigns?
