### ISSUE TITLE
VS Code enhancement: Open angular project from a subfolder

### ISSUE THREAD

**Issue by blahDL** [nrwl/angular-console#561]
When creating a new .net core angular application (via [dotnet new angular](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=netcore-cli)) the angular project exists in the ClientApp folder.  When I open the dotnet core project in VS Code I can't use the extension as it does not find the angular app.

It is possible to have a setting that you can define on the workspace (or similar) that says where to look for angular.json and then use that as the base folder for any angular console tasks that are run?

**Comment by mrmeku** [comment]
@blahDL I'll be working on this feature this week. We had this functionality in an earlier build but the UX was a bit confusing. Hopefully the second attempt is better than the first

**Comment by dlucazeau** [comment]
See #552

**Comment by dungahk** [comment]
I have a similar use case, I have a workspace opened but because it is not just the Angular project, it doesn't work. Looking forward to this! Keep the good work guys!

**Comment by OriginalDrTone** [comment]
Can we make this an enhancement request?

**Comment by mrmeku** [comment]
Fixed!

Via https://github.com/nrwl/angular-console/pull/687

**Comment by mrmeku** [comment]
Sorry it took so long every one

**Comment by OriginalDrTone** [comment]
> Fixed!
> 
> Via #687

I opened my . NET Core project with an Angular workspace in the ClientApp subdirectory and it still doesn't work for me.
